name: unilever-scraping

services:
  rest-auth-gateway:
    build: 
      context: . 
      dockerfile: ./dockerfile
    image:
      unilever-scraping-rest-auth-gateway
    container_name: unilever-scraping-rest-auth-gateway
    ports:
      - "5000:5000"
    volumes:
      - ./app:/home/project_home/project_workdir
    working_dir: /home/project_home/project_workdir
    command: >
      bash -c "
      gunicorn --bind 0.0.0.0:5000 main:app
      "
    networks:
      - shared-network

networks:
  shared-network:
    name: unilever-scraping-network
    external: true
